### ISSUE TITLE
sample code leaks ItemListActivity 

### ISSUE THREAD

**Issue by zaki50** [sys1yagi/indirect-injector#4]
dependency objet with isStrong=true is freed only if context is freed.

If dependency object with isStrong=true is an instance of inner class which belongs to its context, context is never freed. It leads leakage of both context and dependency.

**Comment by sys1yagi** [comment]
Thank you for to point out the problem.
I added releaseDependencies() -> 7ceb6fbfbe8d4b2ab29f46b26f1e4137179edbbf
I will update library to version 0.0.2 soon possible. :+1:
